version: '3.8'

services:
  db:
    image: gvenzl/oracle-xe
    container_name: oracle
    environment:
      ORACLE_ALLOW_REMOTE: "true"
      ORACLE_PASSWORD: 12345678A
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata

volumes:
  oracle_data:
