version: '3.7'

services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: dev
      MYSQL_PASSWORD: 12345678A
      MYSQL_ROOT_PASSWORD: 12345678A
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - backend-network 

networks:
  backend-network:
    name: backend-network
    driver: bridge

volumes:
  mysql:
  